### ISSUE TITLE
Version Switch Broken with sh

### ISSUE THREAD

**Issue by tsawyer** [InterLinked1/phreakscript#29]
Performing `phreaknet install --version xx.x.x` on a new and updated Debian 12 breaks with
```
phreaknet install -b --version 20.4.0
Real time pusling is not compatible or has been disabled for this build.
WARNING: You are installing Asterisk to run as root. This is not recommended.
Specify -u or --user to specify a run user

Starting installation with country code 1
Installing prerequisites...
4507
Package updates occured recently, skipping...
/usr/local/sbin/phreaknet: 1933: Bad substitution
```
Changing the shebang line from sh to bash allows the install to complete.

**Comment by InterLinked1** [comment]
> Performing `phreaknet install --version xx.x.x` on a new and updated Debian 12 breaks with
> 
> ```
> phreaknet install -b --version 20.4.0
> Real time pusling is not compatible or has been disabled for this build.
> WARNING: You are installing Asterisk to run as root. This is not recommended.
> Specify -u or --user to specify a run user
> 
> Starting installation with country code 1
> Installing prerequisites...
> 4507
> Package updates occured recently, skipping...
> /usr/local/sbin/phreaknet: 1933: Bad substitution
> ```
> 
> Changing the shebang line from sh to bash allows the install to complete.

Thanks for the catch, if you try `phreaknet update` does it work now?

**Comment by tsawyer** [comment]
I didn't let this finish because this computer is doing other things, but it looks like it's working...
```
phreaknet install -v 20.5.0
Real time pusling is not compatible or has been disabled for this build.
WARNING: You are installing Asterisk to run as root. This is not recommended.
Specify -u or --user to specify a run user

Starting installation with country code 1
Installing prerequisites...
724
Package updates occured recently, skipping...
Proceeding to install Asterisk 20.5.0...
***************************** WARNING *****************************
PhreakScript IS NOT TESTED WITH OLDER VERSIONS OF ASTERISK!!!
Proceed at your own risk...
asterisk-20.5.0.tar.gz                      73%[================================================================>                        ]  19.69M  2.51MB/s    eta 4s     ^C
```
