### ISSUE TITLE
Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key:

### ISSUE THREAD

**Issue by vacumet** [InterLinked1/phreakscript#55]
Hello
I get this error message in my log files:
[Dec 10 04:00:11] WARNING[1540]: res_phreaknet.c:1102 gen_keypair: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory

The file is there and owned by asterisk:
root@retronet-asterisk:~# ls -lah /var/lib/asterisk/keys/phreaknetrsa*
-rw------- 1 asterisk asterisk 912 Dec  5 21:14 /var/lib/asterisk/keys/phreaknetrsa.key
-rw-r--r-- 1 asterisk asterisk 272 Dec  5 21:14 /var/lib/asterisk/keys/phreaknetrsa.pub

Any ideas why?

**Comment by InterLinked1** [comment]
Not really off the top of my head. Does this issue reproduce regularly, or did this happen just once?

**Comment by vacumet** [comment]
Seems to be daily at 4 in the morning:
`root@retronet-asterisk:/var/log/asterisk# grep rename messages*
messages.log.1:[Dec  8 04:00:59] WARNING[1540] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log.1:[Dec  9 04:00:40] WARNING[1540] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log.1:[Dec 10 04:00:11] WARNING[1540] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log.1:[Dec 11 04:00:48] WARNING[1540] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log.1:[Dec 12 04:00:00] WARNING[20040] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log.1:[Dec 13 04:00:37] WARNING[20040] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log.1:[Dec 14 04:00:13] WARNING[20040] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory
messages.log:[Dec 15 04:00:50] WARNING[20040] res_phreaknet.c: Failed to rename file to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory`

I looked at res/res_phreaknet.c and found keyrotate_hour that is set to 4

**Comment by InterLinked1** [comment]
Could you post the output of your `core show settings`? I wonder if this has to do with permissions on the source file for some reason. It should be `phreaknetrsa.key`, but I don't recall if that's created in the current running directory or elsewhere.

**Comment by vacumet** [comment]
The keys were created by following the following lines from the guide:

cd /var/lib/asterisk/keys/
astgenkey -q -n phreaknetrsa
cat phreaknetrsa.pub # upload your public key at https://portal.phreaknet.org/rsa
touch /etc/asterisk/iax-phreaknet-rsa-in.conf
touch /etc/asterisk/iax-phreaknet-rsa-out.conf

Here is the output of core show settings:

retronet-asterisk*CLI> core show settings

PBX Core settings
-----------------
  Version:                     22.1.0
  ABI related Build Options:   OPTIONAL_API
  All Build Options:           BUILD_NATIVE, OPTIONAL_API
  Maximum calls:               Not set
  Maximum open file handles:   1024
  Root console verbosity:      3
  Current console verbosity:   8
  Debug level:                 0
  Trace level:                 0
  Dump core on crash:          Yes
  Core dump file:              |/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E
  Maximum load average:        0.000000
  Minimum free memory:         0 MB
  Startup time:                19:12:40
  Last reload time:            21:53:07
  System:                      Linux/6.8.0-49-generic built by root on x86_64 2024-12-05 20:43:15 UTC
  System name:
  Entity ID:                   00:50:56:a7:fe:68
  PBX UUID:                    fb158a01-006e-4efa-8d56-53a9eeef1e91
  Default language:            en
  Language prefix:             Enabled
  User name and group:         /
  Running directory:           /
  Executable includes:         Disabled
  Transcode via SLIN:          Enabled
  Transmit silence during rec: Disabled
  Generic PLC:                 Enabled
  Generic PLC on equal codecs: Disabled
  Hide Msg Chan AMI events:    Disabled
  Sounds search custom dir:    Disabled
  Min DTMF duration::          80
  Cache media frames:          Enabled
  RTP use dynamic payloads:    1
  RTP dynamic payload types:   35-63,96-127

* Subsystems
  -------------
  Manager (AMI):               Disabled
  Web Manager (AMI/HTTP):      Disabled
  Call data records:           Enabled
  Realtime Architecture (ARA): Disabled

* Directories
  -------------
  Configuration file:          /etc/asterisk/asterisk.conf
  Configuration directory:     /etc/asterisk
  Module directory:            /usr/lib/asterisk/modules
  Spool directory:             /var/spool/asterisk
  Log directory:               /var/log/asterisk
  Run/Sockets directory:       /var/run/asterisk
  PID file:                    /var/run/asterisk/asterisk.pid
  VarLib directory:            /var/lib/asterisk
  Data directory:              /var/lib/asterisk
  ASTDB:                       /var/lib/asterisk/astdb
  IAX2 Keys directory:         /var/lib/asterisk/keys
  AGI Scripts directory:       /var/lib/asterisk/agi-bin
  Cache directory:             /var/cache/asterisk

**Comment by InterLinked1** [comment]
Interesting, it looks like you created the keys manually, rather than letting PhreakScript or `res_phreaknet` do it for you, which should set the permissions appropriately, but it also seems Asterisk is running as root, so I'm not sure why that would cause an issue then. And I see the keys are owned by the `asterisk` user.

Could you try using one of the automated methods to generate the keys and see if that helps? (See `phreaknet help` for PhreakScript, or `phreaknet` + TAB complete for `res_phreaknet` way).

**Comment by vacumet** [comment]
Asterisk runs as the user and group asterisk
asterisk   48880  1.1  1.0 2266860 84672 ?       Ssl  06:15   5:35 /usr/sbin/asterisk -U asterisk -G asterisk

The only thing running as root in the logs above is me :)

**Comment by InterLinked1** [comment]
> Asterisk runs as the user and group asterisk asterisk 48880 1.1 1.0 2266860 84672 ? Ssl 06:15 5:35 /usr/sbin/asterisk -U asterisk -G asterisk
> 
> The only thing running as root in the logs above is me :)

Interesting, usually that should be reflected in the run user and group:

```
User name and group: /
Running directory: /
```

It might have to do with the running directory, it may be that it's related to that. I'll take a look and let you know.

**Comment by vacumet** [comment]
i checked /etc/default/asterisk
AST_USER="asterisk"
AST_GROUP="asterisk"


root@retronet-asterisk:/etc/asterisk# phreaknet keygen --rotate
Rotating keys...
Generating SSL key 'phreaknetrsa':
writing RSA key
Key length: 272
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDGiQBHc7tbcj0Pokf89lXrn6G/
IHdUZ2bGGmfYui8Svqw5Ko7WR3fRPe8J94A0pJxjHLErta7g2j2p1NyrNXUDdUnX
1/ddQWhNUMMiluF2PglG3NwNG7Qe7fgsQCS75T3+H2sXgdf5VTUf+SELpB2JYhhK
+jFYKJeHUd4Dx9F4jQIDAQAB
-----END PUBLIC KEY-----
Autodetected WAN IP address is 193.234.118.49
Autodetected WAN FQDN hostname is 19323411849.ip.84grams.net.
Attempting to upload RSA public key...
RSA public key updated.
Module 'res_crypto' reloaded successfully.
Key Name           Type     Status           Sum
------------------ -------- ---------------- --------------------------------
phreaknet-rsa-voip.dto.io PUBLIC   [Loaded]         234ca45719d3d46088a4e7687730cc4e
phreaknet-rsa-voip.samuelrey.com PUBLIC   [Loaded]         55e094ad84e694250243865ea46b4acc
phreaknet-rsa-gsee. PUBLIC   [Loaded]         1a518ef476d678352fd61f93c6e725c9
phreaknet-rsa-glasstty.com PUBLIC   [Loaded]         4cf7983cf812febaf69c2bdb9c1b969f
phreaknet-rsa-asteriskoc.ddns.net PUBLIC   [Loaded]         8b6296fe6252d02877864f5d0edc90c3
phreaknet-rsa-knigh PUBLIC   [Loaded]         b223161c94fea127817f81e410b473b9
phreaknet-rsa-xyz.ragefurnace.org PUBLIC   [Loaded]         8383e32925386d23b534e065bf965306
phreaknetrsa       PUBLIC   [Loaded]         ae3781e5851edd34341b1aa885eca10e
phreaknet-rsa-asterisk.crusty.computer PUBLIC   [Loaded]         0e4eb812cec4b73389f47be31ea34218
phreaknet-rsa-sip.westmark.com PUBLIC   [Loaded]         a1c7bf3f63f34a06d6b0e2e209f87319
phreaknet-rsa-phreaknet.apexbs.net PUBLIC   [Loaded]         2842e2cf14a8ea130e3fe8264597c64e
phreaknet-rsa-primis.org PUBLIC   [Loaded]         41f752ee5cbef0f4f0d414df45e60fe8
phreaknet-rsa-159.223.118.137 PUBLIC   [Loaded]         b239cb5b4c32a66b7df27c5ccc207edd
phreaknet-rsa-davephreak.ddns.net PUBLIC   [Loaded]         0dba408522bd65a1bca0b065f3940637
phreaknet-rsa-486DX.net PUBLIC   [Loaded]         e05253c652082a18f8bf9b30d433daad
phreaknet-rsa-pn   PUBLIC   [Loaded]         c505029853fcff88d4de97e160538192
phreaknet-rsa-voip.phreaknet.org PUBLIC   [Loaded]         71820554c5515119097a05b70d5f7b15
phreaknet-rsa-PHLAPABRDS0.philtel.org PUBLIC   [Loaded]         98d81ee1d963ff394c42dc7c8a8cc5fd
phreaknet-rsa-pbx.jfloren.net PUBLIC   [Loaded]         55aa462235e6daee49c39908b72834bc
phreaknet-rsa-pbx.mukaisu.com PUBLIC   [Loaded]         62ac24b6eec18fe20ec082b1c09a6908
phreaknet-rsa-modem PUBLIC   [Loaded]         8846696b744e29b6b5505e6180f96a8a
phreaknet-rsa-141.8.120.154 PUBLIC   [Loaded]         9612569d9c8f59a245e46c9284bbcf9c
phreaknet-rsa-r2.cjcdsb.com PUBLIC   [Loaded]         5d3962f4ff0fd79f757e37d329277fe4
phreaknet-rsa-phreaknet.dialup.world PUBLIC   [Loaded]         e1f5547a2cd2e862c279932b1fb9f052
phreaknet-rsa-phreakpbx.hojoworks.com PUBLIC   [Loaded]         7f7c833452195d555944405cf86a52f0
phreaknet-rsa-sip.magicandroidapps.com.4570 PUBLIC   [Loaded]         65c2bda42083f5faf2fc30ed003f7491
phreaknet-rsa-pbx2.ramsaso.com PUBLIC   [Loaded]         b6114121020a6a7d6199a35afaf03127
phreaknet-rsa-cnet.bluefeathertech.com PUBLIC   [Loaded]         66068b76b8c4f0d6782346866683d2fc
phreaknet-rsa-portal.hivecore.org PUBLIC   [Loaded]         d2dfefbcc365d4e128f4572bb4935e23
phreaknet-rsa-97.100.239.75 PUBLIC   [Loaded]         d47e3ca8650456f8159a31560fb02b95
phreaknet-rsa-freepbx.kjsl.com PUBLIC   [Loaded]         0b6975a18ae40833b9d8a98440fc3195
phreaknet-rsa-modemgw-rdu.serialport.org PUBLIC   [Loaded]         44b6a48ae16ba7c174f1b8e447c2c117
phreaknet-rsa-pbx.praetor.tel PUBLIC   [Loaded]         a44bce8a0125c90a8eaa6d6ea07137a6
phreaknet-rsa-97.95.168.229 PUBLIC   [Loaded]         3e9b623e8b7646f8cd061d586130ea8f
phreaknet-rsa-dial.tfsi.dev PUBLIC   [Loaded]         2329fc1f594b5088b1ee8c0581d5af04
phreaknet-rsa-comun.se PUBLIC   [Loaded]         be59c218734da4a47192a80b1f6ec536
phreaknet-rsa-glenwood.pepperland.cloud PUBLIC   [Loaded]         ea84092b5206dac2657d0f02efb1e935
phreaknet-rsa-switch.phreaknet.org PUBLIC   [Loaded]         ae811d392e6a29975cdf4b26eef34271
phreaknet-rsa-elmcrest.ddns.net PUBLIC   [Loaded]         cb8e20e3768f33d747f97a6fba718407
phreaknet-rsa-71.212.106.25 PUBLIC   [Loaded]         00cbbadb201db26b72ab26cb22df2843
phreaknet-rsa-asterisk.bagpuss.nu PUBLIC   [Loaded]         cf28c82461d42d79b09c5038b3dadb23
phreaknet-rsa-blander.ddnsfree.com PUBLIC   [Loaded]         a905002c87aa4edb663981f4007e5fb7
phreaknet-rsa-PHLAPASODS0.philtel.org.4570 PUBLIC   [Loaded]         f27bb917104c525f5a75efeff07f9e98
phreaknet-rsa-roadriverrail.mdns.org PUBLIC   [Loaded]         e4fddb1ffbcfa2c95593d1dc6149555c
phreaknet-rsa-chaz.nyc PUBLIC   [Loaded]         000cbe4af7661261c57daff7e925a2dc
phreaknet-rsa-wolfriverphone.com PUBLIC   [Loaded]         f179985384a164f2023dbd18821d1330
phreaknet-rsa-cy2.cybre.tel PUBLIC   [Loaded]         0d18ec7c43bcb5c06fd92644aea44da9
phreaknet-rsa-phreak.lightni.ng PUBLIC   [Loaded]         f425dc416cc0201aa115e845efbab0c4
phreaknet-rsa-voip.den.feralfox.net PUBLIC   [Loaded]         5d41e3845fa623ecc73211619644ebdb

49 known RSA keys.

Let's see what will happen tonight

**Comment by vacumet** [comment]
Been busy the last couple of days but i checked. Same message in the logs at 04:00 every night.

**Comment by InterLinked1** [comment]
Could you try applying the patch on this branch and see if that helps with your issue?

https://github.com/InterLinked1/phreakscript/tree/phreaknet-keypair

**Comment by InterLinked1** [comment]
> Could you try applying the patch on this branch and see if that helps with your issue?
> 
> https://github.com/InterLinked1/phreakscript/tree/phreaknet-keypair

Also, instead of waiting for 4am local time, you should be able to test on demand by running `phreaknet keypair create` from within the Asterisk CLI.

**Comment by vacumet** [comment]
Thank you

I tried to patch but I fail. 
When run phreaknet update it says I already have the latest version.
I see no option select the branch when i run the phreaknet command.

I tried to download the changed file and then i ran 
phreaknet install --dahdi --drivers --user=asterisk --force but it seems like it replaced the file i replaced before compiling

**Comment by InterLinked1** [comment]
> Thank you
> 
> I tried to patch but I fail. When run phreaknet update it says I already have the latest version. I see no option select the branch when i run the phreaknet command.
> 
> I tried to download the changed file and then i ran phreaknet install --dahdi --drivers --user=asterisk --force but it seems like it replaced the file i replaced before compiling

It's a patch file, meant to be applied to your existing install.

Starting with what you have, download the patch to the Asterisk source directory and run `git apply PATCH-FILE-NAME.diff`. It should say it applied, then run `make && make install`, restart Asterisk, and see how it fares.

**Comment by vacumet** [comment]
**Before patch:**
retronet-asterisk*CLI> phreaknet keypair rotate
Command 'phreaknet keypair rotate ' failed.
[Dec 20 21:09:34] WARNING[61395]: res_phreaknet.c:1058 gen_keypair: Can't rotate key phreaknetrsa, because it doesn't currently exist?

**.diff file?**
Then i tried to find a .diff file. Couldn't find it so i downloaded the file instead an replaced the old file:
root@retronet-asterisk:/etc/asterisk# cd /usr/src/asterisk-22.1.0/
root@retronet-asterisk:/usr/src/asterisk-22.1.0# cd res
root@retronet-asterisk:/usr/src/asterisk-22.1.0/res# rm res_phreaknet.c
root@retronet-asterisk:/usr/src/asterisk-22.1.0/res# wget https://raw.githubusercontent.com/InterLinked1/phreakscript/bd6ef0d0286d7c3116cf99de20531afcca15c314/res/res_phreaknet.c
--2024-12-20 21:18:55--  https://raw.githubusercontent.com/InterLinked1/phreakscript/bd6ef0d0286d7c3116cf99de20531afcca15c314/res/res_phreaknet.c
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73297 (72K) [text/plain]
Saving to: ‘res_phreaknet.c’

res_phreaknet.c                                         100%[==============================================================================================================================>]  71.58K  --.-KB/s    in 0.01s

2024-12-20 21:18:56 (6.66 MB/s) - ‘res_phreaknet.c’ saved [73297/73297]

root@retronet-asterisk:/usr/src/asterisk-22.1.0/res# cd ..
root@retronet-asterisk:/usr/src/asterisk-22.1.0# make && make install

After compilation was done i restarted asterisk.

**After "patch"**
retronet-asterisk*CLI> phreaknet keypair rotate
Command 'phreaknet keypair rotate' failed.
[Dec 20 21:21:04] WARNING[75305]: res_phreaknet.c:1104 gen_keypair: Failed to rename /tmp/phreaknetrsaphreaknetrsa.key to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory

I guessed that the filename phreaknetrsaphreaknetrsa was the problem, looked at the code and on line 1036 i removed MY_KEYPAIR_NAME as later lines look like this:

ast_log(LOG_WARNING, "Failed to rename %s to %s: %s\n", MY_KEYPAIR_TEMPFILE_PREFIX MY_KEYPAIR_NAME ".key", privkeyfile, strerror(errno));

Then i recompiled again.

**After the fixed patch**
Command 'phreaknet keypair rotate' failed.
[Dec 20 21:27:25] WARNING[85003]: res_phreaknet.c:1104 gen_keypair: Failed to rename /tmp/phreaknetrsa.key to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory

**Comment by InterLinked1** [comment]
Thanks, yes, there is a typo, but only in the log message so that isn't quite it.

What happens if you manually run this command as the user `asterisk`? (e.g. using `su`)

`astgenkey -q -n /tmp/phreaknetrsa`

And then `ls -la /tmp`

I'm thinking maybe that `astgenkey` is failing to create the files in a way that isn't being captured at the moment.

**Comment by vacumet** [comment]
asterisk@retronet-asterisk:~$ whoami
asterisk
asterisk@retronet-asterisk:~$ astgenkey -q -n /tmp/phreaknetrsa
Generating SSL key '/tmp/phreaknetrsa':
writing RSA key

asterisk@retronet-asterisk:~$ ls -la /tmp
total 88
drwxrwxrwt 16 root     root     4096 Dec 21 09:51 .
drwxr-xr-x 24 root     root     4096 Dec  9 21:46 ..
-rw-r--r--  1 asterisk asterisk  185 Dec 15 23:26 debug
drwxrwxrwt  2 root     root     4096 Dec  7 20:53 .font-unix
drwxrwxrwt  2 root     root     4096 Dec  7 20:53 .ICE-unix
**-rw-------  1 asterisk asterisk  916 Dec 21 04:00 .key**
drwx------  2 root     root     4096 Dec  9 21:55 mc-root
**-rw-------  1 asterisk asterisk  916 Dec 21 09:51 phreaknetrsa.key
-rw-rw-r--  1 asterisk asterisk  272 Dec 21 09:51 phreaknetrsa.pub**
-rw-r--r--  1 root     root      211 Dec 17 20:26 phreaknet_upstream_version.txt
**-rw-r--r--  1 asterisk asterisk  272 Dec 21 04:00 .pub**
drwx------  2 root     root     4096 Dec  7 20:53 snap-private-tmp
drwx------  2 comun    comun    4096 Dec 21 09:50 ssh-GeGemYFzHi
drwx------  3 root     root     4096 Dec 11 06:19 systemd-private-63eb06e577bf411ca204615afd65c7a9-ModemManager.service-lm6w2y
drwx------  3 root     root     4096 Dec  7 20:53 systemd-private-63eb06e577bf411ca204615afd65c7a9-ntpsec.service-EHsvYT
drwx------  3 root     root     4096 Dec 11 06:19 systemd-private-63eb06e577bf411ca204615afd65c7a9-polkit.service-tdavBB
drwx------  3 root     root     4096 Dec  7 20:53 systemd-private-63eb06e577bf411ca204615afd65c7a9-systemd-logind.service-83mzNF
drwx------  3 root     root     4096 Dec  7 20:53 systemd-private-63eb06e577bf411ca204615afd65c7a9-systemd-resolved.service-C0nhHb
drwx------  3 root     root     4096 Dec  7 21:05 systemd-private-63eb06e577bf411ca204615afd65c7a9-upower.service-bWd2bB
drwx------  2 root     root     4096 Dec  7 20:53 vmware-root_736-2991268455
drwxrwxrwt  2 root     root     4096 Dec  7 20:53 .X11-unix
drwxrwxrwt  2 root     root     4096 Dec  7 20:53 .XIM-unix


I see that there are one file called .pub and one file called .key that was created 04.00 
-rw-------  1 asterisk asterisk  916 Dec 21 04:00 .key
-rw-r--r--  1 asterisk asterisk  272 Dec 21 04:00 .pub

I guess that the code that generates the files don't know the file name. Just the extension. 
I think this is related to the line i changed yesterday as the change i did removed the filename from the variable MY_KEYPAIR_TEMPFILE_PREFIX. All other locations in the code that use MY_KEYPAIR_TEMPFILE_PREFIX also use MY_KEYPAIR_NAME so i changed line 1049
from:
        char *const argv[] = { "astgenkey", "-q", "-n", MY_KEYPAIR_TEMPFILE_PREFIX, NULL };

to:
        char *const argv[] = { "astgenkey", "-q", "-n", MY_KEYPAIR_TEMPFILE_PREFIX MY_KEYPAIR_NAME, NULL };

I recompiled renamed my old keys. Then I ran phreaknet keypair create
Command 'phreaknet keypair create' failed.
[Dec 21 10:27:11] WARNING[96266]: res_phreaknet.c:1104 gen_keypair: Failed to rename /tmp/phreaknetrsa.key to /var/lib/asterisk/keys/phreaknetrsa.key: No such file or directory

If i do it manually no issues

**Comment by InterLinked1** [comment]
I updated the PR with another fix, could you give it another try?

If it's easier, just download and replace the entire file from here: https://raw.githubusercontent.com/InterLinked1/phreakscript/refs/heads/phreaknet-keypair/res/res_phreaknet.c

It goes in the `res` directory in your Asterisk source, `make && make install` and restart and test.

**Comment by vacumet** [comment]
Looks like success!
retronet-asterisk*CLI> phreaknet keypair rotate
[Dec 21 18:54:17]     -- Reloading module 'res_crypto.so' (Cryptographic Digital Signatures)
[Dec 21 18:54:17]     -- Loaded PUBLIC key 'phreaknetrsa'
[Dec 21 18:54:17]     -- Loaded PRIVATE key 'phreaknetrsa'
[Dec 21 18:54:17]     -- Successfully rotated PhreakNet keypair
